// <auto-generated />
namespace Mooc.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class init001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init001));
        
        string IMigrationMetadata.Id
        {
            get { return "202001141531061_init001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
