// <auto-generated />
namespace Mooc.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class test100 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test100));
        
        string IMigrationMetadata.Id
        {
            get { return "202001091423179_test100"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
