// <auto-generated />
namespace Mooc.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addCourseApply : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addCourseApply));
        
        string IMigrationMetadata.Id
        {
            get { return "202003160712249_addCourseApply"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
